
USE CENTRAL
GO

CREATE ROLE [ADMIN] -- ACCESO A CATALOGOS Y REPORTES (DMLCompleto)
CREATE ROLE [AUDITOR] -- REPORTES(VIZUALIZACION, INSERCION) Y CATALOGOS(VIZUALIZACION)
GO

CREATE USER [ADM01] FOR LOGIN [ADMIN_01] WITH DEFAULT_SCHEMA = [DBO]
CREATE USER [ADM02] FOR LOGIN [ADMIN_02] WITH DEFAULT_SCHEMA = [DBO]
GO
CREATE USER [ADT01] FOR LOGIN [AUDITOR_01] WITH DEFAULT_SCHEMA = [DBO]
CREATE USER [ADT02] FOR LOGIN [AUDITOR_02] WITH DEFAULT_SCHEMA = [DBO]
GO

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::[CATALOGOS] TO [ADMIN]
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::[REPORTES] TO [ADMIN]
GO

ALTER ROLE [ADMIN] ADD MEMBER [ADM01]
ALTER ROLE [ADMIN] ADD MEMBER [ADM02]
GO

GRANT SELECT, INSERT, UPDATE ON SCHEMA::[REPORTES] TO [AUDITOR]
GO
ALTER ROLE [AUDITOR] ADD MEMBER [ADT01]
ALTER ROLE [AUDITOR] ADD MEMBER [ADT02]
GO

USE OPERACIONES
GO

CREATE ROLE [ADMIN]  -- ACCESO A CATALOGOS_REPLICAS Y PAGOS (DMLCompleto)
CREATE ROLE [CAJERO] -- Pagos ( SELECT, INSERT, EJECUCIONES )
CREATE ROLE [AUDITOR] -- Pagos ( EJECUCION )

CREATE USER [ADM01] FOR LOGIN [ADMIN_01] WITH DEFAULT_SCHEMA = [DBO]
CREATE USER [ADM02] FOR LOGIN [ADMIN_02] WITH DEFAULT_SCHEMA = [DBO]
GO
CREATE USER [ADT01] FOR LOGIN [AUDITOR_01] WITH DEFAULT_SCHEMA = [DBO]
CREATE USER [ADT02] FOR LOGIN [AUDITOR_02] WITH DEFAULT_SCHEMA = [DBO]
GO
CREATE USER [CAJ01] FOR LOGIN [CAJERO_01] WITH DEFAULT_SCHEMA = [DBO]
CREATE USER [CAJ02] FOR LOGIN [CAJERO_02] WITH DEFAULT_SCHEMA = [DBO]
GO

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::[CATALOGOS_REPLICAS] TO [ADMIN]
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::[PAGOS] TO [ADMIN]
GO
ALTER ROLE [ADMIN] ADD MEMBER [ADM01]
ALTER ROLE [ADMIN] ADD MEMBER [ADM02]
GO

GRANT EXECUTE ON [Pagos].[sp_crearTiquete] TO [CAJERO]
GRANT SELECT, INSERT ON [Pagos].[tiquetes] TO [CAJERO]
GRANT SELECT ON SCHEMA::[CATALOGOS_REPLICAS] TO [CAJERO]
GO
ALTER ROLE [CAJERO] ADD MEMBER [CAJ01]
ALTER ROLE [CAJERO] ADD MEMBER [CAJ02]
GO

GRANT EXECUTE ON [Pagos].[sp_generarReporteVentasCentralizado] TO [AUDITOR]
GRANT SELECT ON [Pagos].[tiquetes] TO [AUDITOR]
GO
ALTER ROLE [AUDITOR] ADD MEMBER [ADT01]
ALTER ROLE [AUDITOR] ADD MEMBER [ADT02]
GO

USE TLOG
GO

CREATE ROLE [INSERCION_DATOS_BITACORA]
GO

CREATE USER [ADM01] FOR LOGIN [ADMIN_01] WITH DEFAULT_SCHEMA = [DBO]
CREATE USER [ADM02] FOR LOGIN [ADMIN_02] WITH DEFAULT_SCHEMA = [DBO]
GO
CREATE USER [ADT01] FOR LOGIN [AUDITOR_01] WITH DEFAULT_SCHEMA = [DBO]
CREATE USER [ADT02] FOR LOGIN [AUDITOR_02] WITH DEFAULT_SCHEMA = [DBO]
GO
CREATE USER [CAJ01] FOR LOGIN [CAJERO_01] WITH DEFAULT_SCHEMA = [DBO]
CREATE USER [CAJ02] FOR LOGIN [CAJERO_02] WITH DEFAULT_SCHEMA = [DBO]
GO

GRANT INSERT ON [dbo].[TransationLog] TO [INSERCION_DATOS_BITACORA]

ALTER ROLE [INSERCION_DATOS_BITACORA] ADD MEMBER [ADM01]
ALTER ROLE [INSERCION_DATOS_BITACORA] ADD MEMBER [ADM02]
ALTER ROLE [INSERCION_DATOS_BITACORA] ADD MEMBER [ADT01]
ALTER ROLE [INSERCION_DATOS_BITACORA] ADD MEMBER [ADT02]
ALTER ROLE [INSERCION_DATOS_BITACORA] ADD MEMBER [CAJ01]
ALTER ROLE [INSERCION_DATOS_BITACORA] ADD MEMBER [CAJ02]