USE MASTER
GO
CREATE LOGIN [AUDITOR_01] WITH PASSWORD=N'123456', DEFAULT_DATABASE=[master], 
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [AUDITOR_02] WITH PASSWORD=N'123456', DEFAULT_DATABASE=[master], 
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [ADMIN_01] WITH PASSWORD=N'123456', DEFAULT_DATABASE=[master], 
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [ADMIN_02] WITH PASSWORD=N'123456', DEFAULT_DATABASE=[master], 
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [CAJERO_01] WITH PASSWORD=N'123456', DEFAULT_DATABASE=[master], 
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [CAJERO_02] WITH PASSWORD=N'123456', DEFAULT_DATABASE=[master], 
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO